include::ROOT:partial$abbr.adoc[]
:slug: use-the-generic-file-based-runner-integration

= `file` profile for unsupported test runners

[NOTE]
--
This is a reference page. For more comprehensive usage guidelines, refer to xref:send-data-to-smart-tests:set-up-smart-tests/getting-started.adoc[Getting Started], xref:send-data-to-smart-tests:/send-data-to-smart-tests.adoc[Send data to {PRODUCT}], and xref:features:predictive-test-selection.adoc[Predictive test selection].
--

== About

The "file based" test runner integration is primarily designed to work with test runners that are not explicitly supported, such as custom test runners built in-house.

In order to work with {PRODUCT} through this integration mechanism, your test runner has to satisfy the following conditions:

. *File based test runner*: your test runner must accept file names as an input of a test execution in order to execute just those specified set of tests.
. *JUnit XML reports include file names/paths*: your test runner has to produce results of tests in a JUnit compatible format _with_ additional attributes that capture the *file names/paths* of the tests that run. If not, refer to xref:send-data-to-smart-tests:record-test-results/convert-test-reports-to-junit-format.adoc[Convert test reports to JUnit format].

For example, link:https://mochajs.org/#getting-started[Mocha] is a test runner that meets those criteria. You write tests in JavaScript files:

[source]
----
$ cat foo.js
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal([1, 2, 3].indexOf(4), -1);
    });
  });
});
----

The Mocha test runner takes those files as arguments:

`$ mocha --reporter mocha-junit-reporter foo.js`

This produces JUnit report files, where the name of the test file is captured, in this case, in the `file` attribute:

[source]
----
$ cat test-results.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="0">
  <testsuite name="#indexOf()" file="/home/kohsuke/ws/foo.js" ...>
    <testcase  ... />
...
----

The rest of this document uses Mocha as an example.

== Record test results

After running tests, point the CLI to your test report files to collect test results and train the model:

`smart-tests record tests file --build <BUILD NAME> --session <SESSION_NAME> ./reports/*.xml`

[WARNING]
--
You might need to take extra steps to make sure that `smart-tests record tests` always runs even if the build fails. For more information, refer to xref:send-data-to-smart-tests:record-test-results/ensure-record-tests-always-runs.adoc[].
--

== Subset your test runs

The high level flow for subsetting is:

. Get the full list of test files and pass that to `smart-tests subset` with an optimization target for the subset.
. `smart-tests subset` will get a subset from the {PRODUCT} platform and output that list to a text file.
. Pass the text file into your test runner to run only those tests.

To retrieve a subset of tests, first pass the full list of test candidates to `smart-tests subset`. For example:

[source]
----
find ./test -name '*.js' | 
smart-tests subset file \
    --build <BUILD NAME> \
    --session <SESSION_NAME> \
    --target 10% \
    --rest smart-tests-remainder.txt \
    > subset.txt
----

* The `--build` should use the same `<BUILD NAME>` value that you used before in `smart-tests record build`.

* The `--confidence` option should be a percentage; we suggest `90%` to start. You can also use `--time` or `--target`.
+
For more information, refer to xref:features:predictive-test-selection.adoc[Subset your test runs].

This creates a file called `smart-tests-subset.txt` that you can pass into your command to run tests:

`mocha $(< smart-tests-subset.txt)`
