package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "embedding",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_knuddels_jtokkit",
        "@maven//:org_apache_httpcomponents_httpclient",
        "@maven//:org_apache_httpcomponents_httpcore",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
