include::ROOT:partial$abbr.adoc[]

= Combine with rule-based test selection
:slug: combine-with-rule-based-test-selection

If you have an existing test selection mechanism or other rule-based test selection mechanisms of the following pattern, you can combine them with {PRODUCT}'s ML-based predictive test selection.

This usually results in sub-optimal performance when finding more failures from test runs, but this can improve psychological safety by making the algorithm more “explainable;" there’s a clear, unambiguous link between committed changes and selected tests.

== Create a rule definition file

Using a rule definition file that maps source directories to tests, you can provide rules to prioritize tests. For example, the following rule snippet says any change under `src/payment` should result in `payment_test.py` and `new_payment_test.py` to be selected automatically:

[source]
----
{ ...
  {
    "src/payment" : ["file=test/payment_test.py", "file=test/new_payment_test.py"]
  }
}
----

The full format of this file is as follows:

[source]
----
{
  "format": "prioritized-tests-v1",
  "mappings": {
    $REPO_NAME: {
      $DIRECTORY: [$TEST_PATH, ...],
      ... // repeatable
    },
    ... // repeatable
  }
}
----

* `$REPO_NAME` refers to the repository name given in `smart-tests record build --source REPO_NAME=DIR` . That’s how the CLI can match the information in the mapping file to what has changed.
* `$DIRECTORY` refers to the relative path within the enclosing repository.
* `$TEST_PATH` is the name of a test represented in {PRODUCT}’s internal test path notation. You can use xref:references:cli-reference.adoc[the inspect tests command] to see the test paths for your recorded tests.

== Use the rule definition file

Pass this definition file through the `--prioritized-tests-mapping` option when making a `smart-tests subset` invocation, as follows:

`smart-tests subset --prioritized-tests-mapping foo/bar/test-mapping.json ...`

== Behaviors of subsetting

Tests selected via mapping rules *are always prioritized first* before {PRODUCT} starts selecting tests based on the estimated likelihood of failures. If the specified optimization target (e.g., `--duration` ) allows for more tests to be selected, then {PRODUCT} will add tests it estimates will be most effective. On the other hand, if tests selected via mapping rules are already too big to fit the goal, some of those tests will be dropped to create a subset that meets the goal.