name: Update maven_install.json
on:
  pull_request:
    paths:
      - 'WORKSPACE'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 8
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: '8'
      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2.0.0
      - name: Cache Bazel outputs
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Update maven_install.json
        run: |
          bazel run @unpinned_maven//:pin
      - name: Commit updated files
        run: |
          if ! git diff --exit-code --quiet
          then
            git add src/maven_install.json
            git config --local user.email "nobody@launchableinc.com"
            git config --local user.name "File Update GitHub Workflow"
            git commit -m "Update maven_install.json"
            git push
          fi
